baseURL = 'https://mathisdesaulty.github.io/'
languageCode = 'fr'
title = 'Mathis Desaulty'
theme = 'terminal'

[params]
  description = "Blog personnel, CTF write-ups et portfolio"
  author = "Mathis Desaulty"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = true

[params.homeInfoParams]
  Title = "ğŸ‘‹ Bienvenue !"
  Content = """
  Je suis Mathis, passionnÃ© de cybersÃ©curitÃ© et dÃ©veloppement.
  
  Explorez mes write-ups CTF, articles de blog et projets !
  """

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/mathisdesaulty"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mathis-desaulty-7277b6263/"  

# Menu principal
[menu]
  [[menu.main]]
    name = "ğŸ  Accueil"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "ğŸš© Write-ups"
    url = "/writeups/"
    weight = 2
  
  [[menu.main]]
    name = "ğŸ“ Blog"
    url = "/blog/"
    weight = 3
  
  [[menu.main]]
    name = "ğŸ’¼ Portfolio"
    url = "/portfolio/"
    weight = 4
  
  [[menu.main]]
    name = "ğŸ·ï¸ Tags"
    url = "/tags/"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = false