baseURL = 'https://mathisdesaulty.github.io/'
languageCode = 'fr'
title = 'Mathis Desaulty'
theme = 'terminal'

[params]
  # Centrer le contenu
  centerTheme = true
  
  # Largeur pleine (optionnel, essayez les deux)
  fullWidthTheme = false
  
  # Couleur du thÃ¨me (green, orange, red, blue, pink)
  themeColor = "green"
  
  # Nombre d'items dans le menu
  showMenuItems = 5
  
  # Type de contenu
  contentTypeName = "posts"
  
  # Logo personnalisÃ©
  [params.logo]
    logoText = "mathis@desaulty:~$"
    logoHomeLink = "/"

# Menu
[[menu.main]]
  identifier = "writeups"
  name = "write-ups"
  url = "/writeups/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  identifier = "portfolio"
  name = "portfolio"
  url = "/portfolio/"
  weight = 3

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[params.homeInfoParams]
  Title = "ğŸ‘‹ Bienvenue !"
  Content = """
  Je suis Mathis, passionnÃ© de cybersÃ©curitÃ© et dÃ©veloppement.
  
  Explorez mes write-ups CTF, articles de blog et projets !
  """

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/mathisdesaulty"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mathis-desaulty-7277b6263/"  

# Menu principal
[menu]
  [[menu.main]]
    name = "ğŸ  Accueil"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "ğŸš© Write-ups"
    url = "/writeups/"
    weight = 2
  
  [[menu.main]]
    name = "ğŸ“ Blog"
    url = "/blog/"
    weight = 3
  
  [[menu.main]]
    name = "ğŸ’¼ Portfolio"
    url = "/portfolio/"
    weight = 4
  
  [[menu.main]]
    name = "ğŸ·ï¸ Tags"
    url = "/tags/"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = false